### ISSUE TITLE
Error with npm start

### ISSUE THREAD

**Issue by akakak1** [wtjs/tooltip#2]
```
Module parse failed: Unexpected token (9:11)
You may need an appropriate loader to handle this file type.
| export var imports = {
|   'docs/index.mdx': function docsIndexMdx() {
>     return import(
|     /* webpackPrefetch: true, webpackChunkName: "docs-index" */
|     'docs/index.mdx');

 @ ./.docz/app/index.jsx 11:0-36 34:13-20 44:2-46:4 44:33-46:3
 @ multi ./node_modules/babel-polyfill/lib/index.js ./.docz/app/index.jsx
```

**Comment by divyanshu013** [comment]
Can you please try with `yarn` instead? Remove the `node_modules` first and then install the dependencies by running `yarn` at the project root. Let me know if this resolves the issue.

**Comment by akakak1** [comment]
Ya it works perfect with `yarn`  
Thanks.

How to resolve the error with npm ?

**Comment by divyanshu013** [comment]
I think the issue is with some dependency. We already have a lockfile for yarn which would ensure the correct deps. I guess this would need a similar `package-lock.json` file for npm to work without hiccups. Please use `yarn` for now.
